# Generated by Django 5.0.6 on 2024-05-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kajak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seats", models.PositiveSmallIntegerField()),
                (
                    "color",
                    models.CharField(
                        choices=[("RED", "red"), ("GREEN", "green")], max_length=16
                    ),
                ),
                ("cargo", models.BooleanField(default=False)),
                ("cup_holder", models.BooleanField(default=False)),
                (
                    "kajak_type",
                    models.CharField(
                        choices=[
                            ("SPORT", "sport"),
                            ("RECREATIONAL", "recreational"),
                            ("KIDS", "kids"),
                        ],
                        max_length=16,
                    ),
                ),
                ("price_per_hour", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
